swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /transactions/{month}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transactions of specific month
      description: API for fetching all transactions of the specific month
      parameters:
        - in: path
          name: month
          description: month
          required: true
          type: integer
      responses:
        "200":
          description: Transactions data successfully fetched
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ApiTransactionResponses"
        "401":
          description: No Authorization
          schema:
            $ref: "#/definitions/ApiTransactionResponses"
        "500":
          description: Internal Server Error
  /transactions/{transactionId}/transaction:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction by id
      description: API for fetching the details of a transaction
      parameters:
        - in: path
          name: transactionId
          description: ID of transaction
          required: true
          type: integer
      responses:
        "200":
          description: Transaction detail data successfully fetched
          schema:
            $ref: "#/definitions/TransactionResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ApiTransactionResponses"
        "401":
          description: No Authorization
          schema:
            $ref: "#/definitions/ApiTransactionResponses"
        "500":
          description: Internal Server Error
  /transactions/{transactionId}/information:
    put:
      tags:
        - Transaction Module
      security:
        - Bearer: []
      summary: Modify information of a transaction
      description: API for modify information of a transaction
      parameters:
        - in: body
          name: body
          description: Modify Payload
          required: true
          schema:
            $ref: "#/definitions/PutInformation"
        - in: path
          name: transactionId
          description: ID of transaction
          required: true
          type: integer
      responses:
        "200":
          description: Transaction information successfully modified
          schema:
            $ref: "#/definitions/ApiTransactionResponses"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ApiTransactionResponses"
        "401":
          description: No Authorization
          schema:
            $ref: "#/definitions/ApiTransactionResponses"
        "500":
          description: Internal Server Error
  /categories:
    get:
      security:
        - Bearer: []
      tags:
        - Category Module
      summary: get all categories of transaction
      description: API for fetching all categories of transaction
      responses:
        "200":
          description: Categories data successfully fetched
          schema:
            $ref: "#/definitions/CategoriesResponse"
        "400":
          description: Bad Request
          schema:
            $ref: "#/definitions/ApiCategoriesResponses"
        "401":
          description: No Authorization
          schema:
            $ref: "#/definitions/ApiCategoriesResponses"
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: integer
          date:
            type: string
          description:
            type: string
          amount:
            type: string
          balance:
            type: string
          informations:
            type: object
            properties:
              transactionType:
                type: string
              category:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
              note:
                type: string
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            account:
              properties:
                id:
                  type: integer
                title:
                  type: string
                amount:
                  type: string
                description:
                  type: string
                transactions:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      date:
                        type: string
                      description:
                        type: string
                      amount:
                        type: string
                      balance:
                        type: string
  ApiTransactionResponses:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
  PutInformation:
    type: object
    properties:
      Note:
        type: string
      CategoryId:
        type: integer
  CategoriesResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
  ApiCategoriesResponses:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
